name: Cypress Tests

on:  
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Get Codec
        uses: actions/checkout@v4.2.2
     
      - name: Instalar dependencias
        run: npm install

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: cypress/reports/html/index.html
