name: Cypress Tests

on:  
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codec
        uses: actions/checkout@v4.2.2
     
      - name: Instalar dependencias
        run: npm install

      - name: Executar Cypress 
        run: npx cypress run
